In [241]:
import numpy as np

votes = np.array([7, 7, 3, 3])

candidates = np.array([
    ['A', 'C', 'D', 'B'],
    ['C', 'A', 'B', 'D'],
    ['B', 'C', 'D', 'A'],
    ['B', 'A', 'C', 'D']
])


In [242]:
def print_result(text, result, value):
    if(result[0] == value):
        text += ' A'
    if(result[1] == value):
        text += ' B'
    if(result[2] == value):
        text += ' C'
    if(result[3] == value):
        text += ' D'
    
    print(text)

In [243]:
def find_relative(candidates, votes):
    result = np.zeros(len(candidates))

    for i in range(len(candidates[0])):
        if(candidates[i, 0] == 'A'):
            result[0] += votes[i]
        if(candidates[i, 0] == 'B'):
            result[1] += votes[i]
        if(candidates[i, 0] == 'C'):
            result[2] += votes[i]
        if(candidates[i, 0] == 'D'):
            result[3] += votes[i]
    
    maxValue = np.max(result)
    print(result)

    print_result('Правило відносної більшості:', result, maxValue)
    

    return result


In [244]:
def find_absolute(candidates, votes):
    letters = np.array(['A', 'B', 'C', 'D'])
    result = find_relative(candidates, votes)

    sort_result = np.argsort(result)

    result[:] = 0

    for i in range(len(candidates)):
        for j in range(len(candidates[0])):
            if candidates[i, j] == letters[sort_result[2]]:
                result[sort_result[2]] += votes[i]
                break
            if candidates[i, j] == letters[sort_result[3]]:
                result[sort_result[3]] += votes[i]
                break
    
    maxValue = np.max(result)

    print(result)
    print_result('Правило абсолютної більшості:', result, maxValue)



find_absolute(candidates, votes)

[7. 6. 7. 0.]
Правило відносної більшості: A C
[10.  0. 10.  0.]
Правило абсолютної більшості: A C


In [245]:
def find_board(candidates, votes):
    k = np.array([3, 2, 1, 0])

    result = np.zeros(len(candidates))

    for i in range(len(candidates)):
        for j in range(len(candidates[0])):
            if(candidates[i, j] == 'A'):
                result[0] += votes[i] * k[j]
            if(candidates[i, j] == 'B'):
                result[1] += votes[i] * k[j]
            if(candidates[i, j] == 'C'):
                result[2] += votes[i] * k[j]
            if(candidates[i, j] == 'D'):
                result[3] += votes[i] * k[j]

    maxValue = np.max(result)
    print(result)
    print_result('Правило Борда:', result, maxValue)

find_board(candidates, votes)

[41. 25. 44. 10.]
Правило Борда: C


In [246]:
def find_Condorcet(candidates, votes):
    letters = np.array(['A', 'B', 'C', 'D'])

    result = np.zeros((len(candidates), len(candidates)))

    for i in range(len(result)):
        for j in range(len(result[0])):
            if i == j: result[i, j] = 0

            else:
                for l in range(len(candidates)):
                    for k in range(len(candidates[0])):
                        if candidates[l, k] == letters[j]:
                            break
                        if candidates[l, k] == letters[i]:
                            result[i, j] += votes[l]
                            break
    return(result)

find_Condorcet(candidates, votes)

array([[ 0., 14., 10., 17.],
       [ 6.,  0.,  6., 13.],
       [10., 14.,  0., 20.],
       [ 3.,  7.,  0.,  0.]])

In [247]:
def find_Copeland(candidates, votes):
    matrix = find_Condorcet(candidates, votes)

    result = np.zeros(len(candidates))

    for i in range(len(matrix)):
        for j in range(i+1, len(matrix[i])):
            if matrix[i, j] > matrix[j, i]:
                result[i] += 1
                result[j] -= 1
            
            if matrix[i, j] < matrix[j, i]:
                result[i] -= 1
                result[j] += 1

    maxValue = np.max(result)
    print(result)
    print_result('Правило Копленда:', result, maxValue)

find_Copeland(candidates, votes)

[ 2. -1.  2. -3.]
Правило Копленда: A C


In [248]:
def find_Simpson(candidates, votes):
    matrix = find_Condorcet(candidates, votes)

    result = np.zeros(len(candidates))

    for i in range(len(matrix)):
        values = []
        for j in range(len(matrix[i])):
            if i != j:
                values.append(matrix[i, j])
        
        result[i] = np.min(values)

    maxValue = np.max(result)
    print(result)
    print_result('Правило Сімпсона:', result, maxValue)

find_Simpson(candidates, votes)

[10.  6. 10.  0.]
Правило Сімпсона: A C
